on:
  workflow_dispatch:

name: main
jobs:
  linux-musl-arm64:
    name: linux musl arm64
    runs-on: ubuntu-24.04-arm
    container:
      image: alpine:3.18
      volumes:
      - /:/host
      - /opt:/opt:rw,rshared
      - /opt:/__e/node24:ro,rshared
      - /opt:/__e/node20:ro,rshared
    strategy:
      fail-fast: false
      matrix:
        architecture: [ arm64 ]
        quantum: [ Q8 ]
    steps:
      - name: Allow Linux musl containers on ARM64 runners
        run: |
          sed -i "/^ID=/s/alpine/NotpineForGHA/" /etc/os-release
          apk add nodejs --update-cache
          mkdir /opt/bin
          ln -s /usr/bin/node /opt/bin/node

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install build tools
        run: chmod a+x ./install.build-tools.sh&&./install.build-tools.sh
        working-directory: build/linux-musl-${{matrix.architecture}}
  
      - name: Update ImageMagick.commit to latest commit
        run: chmod a+x ./update.imagemagick.sh&&./update.imagemagick.sh
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        working-directory: src/ImageMagick
  
      - name: Clone ImageMagick libraries
        run: ./checkout.sh --no-configure --dependencies-artifact linux-musl-${{matrix.architecture}}-static.zip
        working-directory: src/ImageMagick
  
      - name: Build ImageMagick
        run: ../../../build/shared/build.imagemagick.sh linux-musl ${{matrix.architecture}} ${{matrix.quantum}}
        working-directory: src/ImageMagick/ImageMagick
  
      - name: Build Native
        run: ../../build/shared/build.native.sh linux-musl ${{matrix.architecture}} ${{matrix.quantum}}
        working-directory: src/Magick.Native
  
      - name: Copy Native
        run: ../../build/shared/copy.native.sh ../../artifacts linux-musl ${{matrix.architecture}} ${{matrix.quantum}}
        working-directory: src/Magick.Native
  
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: linux-musl-${{matrix.quantum}}-${{matrix.architecture}}-NoOpenMP
          path: artifacts

  metadata:
    name: Metadata
    needs:
      - linux-musl-arm64
    runs-on: ubuntu-24.04
    outputs:
      version: ${{steps.set-version.outputs.version}}

    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Download artifacts
      uses: actions/download-artifact@v5
      with:
        name: windows-Q8-arm64

    - name: Set version
      id: set-version
      run: echo "version=$(date +'%Y.%-m%d.%-H%M')" >> $GITHUB_OUTPUT

    - name: Copy NOTICE.txt and create libraries.md
      run: |
        mkdir -p artifacts/metadata
        cd artifacts/metadata

        cp ../../NOTICE.txt NOTICE.txt

        commit=$(git rev-parse HEAD)
        echo "# Libraries" >> libraries.md
        echo "Magick.Native [$commit](https://github.com/dlemstra/Magick.Native/commit/$commit) is build with the following libraries:" >> libraries.md
        echo "" >> libraries.md
        sed -n 's/^\[ \(.*\) \]/- \1/p' ../../NOTICE.txt >> libraries.md

    - name: Upload metadata
      uses: actions/upload-artifact@v4
      with:
        name: metadata
        path: artifacts
