on:
  workflow_dispatch:

name: main
jobs:
  linux-musl-arm64:
    name: linux musl arm64
    runs-on: ubuntu-24.04-arm
    container:
      image: alpine:3.18
      volumes:
      - /:/host
      - /opt:/opt:rw,rshared
      - /opt:/__e/node24:ro,rshared
      - /opt:/__e/node20:ro,rshared
    strategy:
      fail-fast: false
      matrix:
        architecture: [ arm64 ]
        quantum: [ Q8 ]
    steps:
      - name: Allow Linux musl containers on ARM64 runners
        run: |
          sed -i "/^ID=/s/alpine/NotpineForGHA/" /etc/os-release
          apk add nodejs --update-cache
          mkdir /opt/bin
          ln -s /usr/bin/node /opt/bin/node

      - name: Checkout
        uses: actions/checkout@v5

      - name: Install build tools
        run: chmod a+x ./install.build-tools.sh&&./install.build-tools.sh
        working-directory: build/linux-musl-${{matrix.architecture}}
  
      - name: Update ImageMagick.commit to latest commit
        run: chmod a+x ./update.imagemagick.sh&&./update.imagemagick.sh
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        working-directory: src/ImageMagick
  
      - name: Clone ImageMagick libraries
        run: ./checkout.sh --no-configure --dependencies-artifact linux-musl-${{matrix.architecture}}-static.zip
        working-directory: src/ImageMagick
  
      - name: Build ImageMagick
        run: ../../../build/shared/build.imagemagick.sh linux-musl ${{matrix.architecture}} ${{matrix.quantum}}
        working-directory: src/ImageMagick/ImageMagick
  
      - name: Build Native
        run: ../../build/shared/build.native.sh linux-musl ${{matrix.architecture}} ${{matrix.quantum}}
        working-directory: src/Magick.Native
  
      - name: Copy Native
        run: ../../build/shared/copy.native.sh ../../artifacts linux-musl ${{matrix.architecture}} ${{matrix.quantum}}
        working-directory: src/Magick.Native
  
      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: linux-musl-${{matrix.quantum}}-${{matrix.architecture}}-NoOpenMP
          path: artifacts
